[package]
name = "shell2bin"
version = "2.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/bennett-sh/shell2bin"
homepage = "https://github.com/bennett-sh/shell2bin"
description = "A tool for converting shell scripts to executables"

[dependencies]
tempfile = "3.3.0"
